{
 "title": "EVPN-PROD",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Leaf 1 CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Utilization" }
   ],
   "targets": [
    {
     "alias": "Kernel",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_kernel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "leaf1" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "leaf1" }
     ]
    }
   ]
  },
  {
   "title": "Leaf 2 CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Utilization" }
   ],
   "targets": [
    {
     "alias": "Kernel",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_kernel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "leaf2" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "leaf2" }
     ]
    }
   ]
  },
  {
   "title": "Leaf 3 CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Utilization" }
   ],
   "targets": [
    {
     "alias": "Kernel",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_kernel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "leaf3" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "leaf3" }
     ]
    }
   ]
  },
  {
   "title": "Leaf 4 CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Utilization" }
   ],
   "targets": [
    {
     "alias": "Kernel",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_kernel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "leaf4" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "leaf4" }
     ]
    }
   ]
  },
  {
   "title": "Spine 1 CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Utilization" }
   ],
   "targets": [
    {
     "alias": "Kernel",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_kernel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "spine1" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "spine1" }
     ]
    }
   ]
  },
  {
   "title": "Spine 2 CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Utilization" }
   ],
   "targets": [
    {
     "alias": "Kernel",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_kernel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "spine2" }
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "cpu_state_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Producer", "operator": "=", "value": "spine2" }
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show system resources",
     "select": [
      [
       { "params": [ "memory_usage_used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Established BGP Neighbors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show bgp vrf all sessions",
     "select": [
      [
       { "params": [ "totalestablishedpeers" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Established OSPF Neighbors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 31 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Producer" ], "type": "tag" }
     ],
     "measurement": "show ip ospf neighbors",
     "select": [
      [
       { "params": [ "TABLE_ctx__ROW_ctx__nbrcount" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}